config/routes.rb
Rails.application.routes.draw do
  get 'articles/show'
  get 'avis_sous_thematiques/show'
  get 'avis_thematiques/show'
  get 'sous_thematiques/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :personnalites, only: [:index, :show]
  get '/partis/search', to: 'partis#search'
  resources :partis, only: [:index, :show]
  resources :thematiques, only: [:index, :show] do
    resources :sous_thematiques, only: [:index, :show]
  end
  resources :avis_thematiques, only: [:show]
  resources :avis_sous_thematiques, only: [:show]
  root to: 'pages#home'
  get '/qui-sommes-nous', to: 'pages#about'
  get '/pour-aller-plus-loin', to: 'pages#info'
  resources :articles, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :contenu
  extend FriendlyId
    friendly_id :titre, use: :slugged
end

app/models/avis_sous_thematique.rb
class AvisSousThematique < ApplicationRecord
  belongs_to :sous_thematique
  belongs_to :parti
  validates_uniqueness_of :sous_thematique_id, scope: :parti_id
  has_rich_text :rich_liens
  has_rich_text :rich_avis
end

app/models/avis_thematique.rb
class AvisThematique < ApplicationRecord
  belongs_to :parti, optional: true
  belongs_to :thematique
  attribute :liens, :string, array: true
  validates_uniqueness_of :parti_id, scope: :thematique_id
  has_rich_text :rich_opinion_majoritaire
  has_rich_text :rich_divergences
  has_rich_text :rich_liens
end

app/models/parti.rb
class Parti < ApplicationRecord
  extend FriendlyId
  friendly_id :nom, use: :slugged
  has_one_attached :photo
  has_many :avis_thematiques, dependent: :destroy
  has_many :thematiques, through: :avis_thematiques
  has_many :sous_thematiques, through: :avis_sous_thematiques
  has_many :avis_sous_thematiques, dependent: :destroy
  accepts_nested_attributes_for :avis_thematiques, allow_destroy: true
  accepts_nested_attributes_for :avis_sous_thematiques, allow_destroy: true
  after_create :create_blank_avis_thematiques, :create_blank_avis_sous_thematiques
  after_update :create_blank_avis_thematiques, :create_blank_avis_sous_thematiques
  has_rich_text :rich_description

  def create_blank_avis_thematiques
    thematiques = Thematique.all
    thematiques.each do |thematique|
      AvisThematique.find_or_create_by(parti_id: id, thematique_id: thematique.id)
    end
  end

  def create_blank_avis_sous_thematiques
    sous_thematiques = SousThematique.all
    sous_thematiques.each do |sous_thematique|
      AvisSousThematique.find_or_create_by(parti_id: id, sous_thematique_id: sous_thematique.id)
    end
  end
end

app/models/personnalite.rb
class Personnalite < ApplicationRecord
  extend FriendlyId
  friendly_id :nom, use: :slugged
  belongs_to :parti
  has_rich_text :rich_resume
  has_rich_text :rich_propositions
end

app/models/sous_thematique.rb
class SousThematique < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, use: :slugged
  belongs_to :thematique
  has_many :avis_sous_thematiques, dependent: :destroy
  has_one_attached :photo
  after_create :add_sous_thematique_avis

  def add_sous_thematique_avis
    partis = Parti.all
    sous_thematique = SousThematique.last
    partis.each do |parti|
      AvisSousThematique.create(parti_id: parti.id, sous_thematique_id: sous_thematique.id)
    end
  end
end

app/models/thematique.rb
class Thematique < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, use: :slugged
  has_many :sous_thematiques, dependent: :destroy
  has_many :avis_thematiques, dependent: :destroy
  accepts_nested_attributes_for :sous_thematiques
  has_one_attached :photo
  after_create :add_thematique_avis
  has_rich_text :description

  def add_thematique_avis
    partis = Parti.all
    thematique = Thematique.last
    partis.each do |parti|
      AvisThematique.create(parti_id: parti.id, thematique_id: thematique.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.friendly.find(params[:id])
  end
end

app/controllers/avis_sous_thematiques_controller.rb
class AvisSousThematiquesController < ApplicationController
  def show
  end
end

app/controllers/avis_thematiques_controller.rb
class AvisThematiquesController < ApplicationController
  def show
    # FIX N+1 IF NECESSARY
    @avis_thematique = AvisThematique.find(params[:id])
    @parti = Parti.find(@avis_thematique.parti_id)
    parti_id = @avis_thematique.parti_id
    thematique_id = @avis_thematique.thematique_id
    sous_thematiques = SousThematique.all.where(thematique_id: thematique_id)
    @avis_sous_thematiques = AvisSousThematique.all.where(sous_thematique_id: sous_thematiques, parti: parti_id).with_rich_text_rich_avis
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def info
    @articles = Article.all
  end

  def search
    @results = Parti.search(params[:query], fields: ["nom"])
  end
end

app/controllers/partis_controller.rb
class PartisController < ApplicationController
  def index
    @partis = Parti.order(:nom).includes(photo_attachment: :blob)
  end

  def search
    redirect_to parti_path(params[:search])
  end

  def show
    @parti = Parti.friendly.find(params[:id])
    @avis_thematiques = AvisThematique.where(parti: @parti.id).joins(:thematique).includes(thematique: [photo_attachment: :blob]).order(:titre)
  end
end

app/controllers/personnalites_controller.rb
class PersonnalitesController < ApplicationController
  def index
    @partis = Parti.order(:nom)
    if params[:search].nil?
      @personnalites = Personnalite.all.order(:nom).includes(parti: [photo_attachment: :blob])
    else
      parti = Parti.find(params[:search])
      @personnalites = Personnalite.where(parti_id: parti).order(:nom).includes(parti: [photo_attachment: :blob])
    end
  end

  def show
    @personnalite = Personnalite.friendly.find(params[:id])
  end
end

app/controllers/sous_thematiques_controller.rb
class SousThematiquesController < ApplicationController

  def index
    @sous_thematiques = SousThematique.all.includes(photo_attachment: :blob)
    @partis = Parti.order(:nom)
  end

  def show
    @sous_thematique = SousThematique.friendly.find(params[:id])
    @avis_sous_thematiques = AvisSousThematique.where(sous_thematique_id: @sous_thematique.id).includes(parti: [photo_attachment: :blob]).order('partis.nom').with_rich_text_rich_avis
    @partis = Parti.order(:nom)
    if !params[:search].nil?
      @avis_sous_thematiques = @avis_sous_thematiques.where(parti_id: params[:search]).includes(parti: [photo_attachment: :blob]).order('partis.nom').with_rich_text_rich_avis
    end
  end

end

app/controllers/thematiques_controller.rb
class ThematiquesController < ApplicationController
  def index
    # NEED TO JOIN SOUS THEMATIQUES TO AVOID N+1
    @thematiques = Thematique.all.order(:titre).includes(photo_attachment: :blob).includes(:sous_thematiques)
  end

  def show
    @thematique = Thematique.friendly.find(params[:id])
    @sous_thematiques = @thematique.sous_thematiques.order(:titre).includes(photo_attachment: :blob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
      base_title = 'La Politique en France'
      if page_title.empty?
        base_title
      else
        page_title + ' | ' + base_title
      end
    end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
<!--       <span class="attachment__name"><%#= blob.filename %></span>
      <span class="attachment__size"><%#= number_to_human_size blob.byte_size %></span> -->
    <% end %>
  </figcaption>
</figure>

app/views/articles/show.html.erb
<% provide(:title, @article.titre) %>
<h1><%= @article.titre %></h1>
<p><%= @article.contenu %></p>

app/views/avis_sous_thematiques/show.html.erb
<h1>AvisSousThematiques#show</h1>
<p>Find me in app/views/avis_sous_thematiques/show.html.erb</p>

app/views/avis_thematiques/show.html.erb
<% provide(:title, "#{@avis_thematique.thematique.titre} selon #{@parti.nom}") %>
<div class="custom-wrapper avis_thematique">
  <%= cl_image_tag @parti.photo.key, class: "avis-parti-logo"  %>
  <div class="avis-title-image-container">
    <% if @avis_thematique.thematique.photo.attached? %>
      <%= cl_image_tag @avis_thematique.thematique.photo.key, size: "180x180", crop: "pad", gravity: "center" %>
    <% end %>
    <h1><%= @avis_thematique.thematique.titre %></h1>
  </div>

  <% if !@avis_thematique.rich_opinion_majoritaire.blank? %>
    <p><%= @avis_thematique.rich_opinion_majoritaire %></p>
  <% else %>
    <p>Pas de remarques à ce sujet.</p>
  <% end %>

  <p><%= @avis_thematique.rich_divergences %></p>

  <%# unless @avis_thematique.rich_liens.length == 0 %>
      <p><%= @avis_thematique.rich_liens %></p>
  <%# end %>

  <div class="grid-avis-sous-thematiques">
    <% @avis_sous_thematiques.each do |avis| %>
      <% if avis.rich_avis.body.to_s.length != 37 %>
        <div class="avis-sous-thematiques">
          <h2><%= avis.sous_thematique.titre %></h2>
          <%= avis.rich_avis %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% unless action_name == "home" %>
      <div class="container">
    <% end %>
      <%= yield %>
    <% unless action_name == "home" %>
    </div>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'Qui sommes-nous?') %>
<h1>Qui sommes-nous ?</h1>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="home-wrapper">
    <h1 class="home-explanation">Politique Française, le premier comparateur des partis politiques français. Notre objectif est de rendre les programmes accessibles, faciles à retrouver et à comparer.</h1>

    <div class="home-cards">
      <%= link_to partis_path do %>
        <div class="home-card">
          <h2>Partis Politiques</h2>
          <p>Vous voulez avoir accès au programme complet d'un parti ? C'est par ici !</p>
        </div>
      <% end %>
      <%= link_to thematiques_path do %>
        <div class="home-card">
          <h2>Thématiques</h2>
          <p>Vous souhaitez comparer les programmes sur un sujet spécifique ? C'est par là !</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/info.html.erb
<% provide(:title, 'Pour aller plus loin') %>
<h1>Pour aller plus loin</h1>
<ul class="article-cards">
  <% @articles.each do |article| %>
    <li class="article-card">
      <%= link_to article_path(article) do %>
        <h2><%= article.titre %></h2>
        <i class="fas fa-arrow-right"></i>
      <% end %>
      <p><%= article.resume %></p>
    </li>
  <% end %>
</ul>

app/views/pages/search.html.erb
<% if @results.count == 0 %>
  <p>Nous n'avons rien trouvé. Veuillez reformuler votre recherche.</p>
  <% else %>
  <% @results.each do |result| %>
    <%= result.nom %>
  <% end %>
<% end %>

app/views/partis/index.html.erb
<% provide(:title, 'Partis Politiques') %>
<h1>Partis Politiques</h1>

<p class="page-explanation">Quel parti recherchez-vous ?</p>

<%= form_tag(partis_search_path, method: "get", class: "search-form") do %>
  <div>
    <%= select_tag :search, options_from_collection_for_select(@partis, :id, :nom, params[:search]), class: 'select2' %>
  </div>
  <div>
    <%= submit_tag("Rechercher", class: "custom-search-button") %>
  </div>
<% end %>

<div class="vertical-cards">
  <% @partis.each do |parti| %>
    <% unless parti.nom == "Indépendant" %>
      <%= link_to parti_path(parti), class: "political-card" do %>
          <div class="card-image">
            <% if parti.photo.attached? %>
              <%= cl_image_tag parti.photo.key, class: "zoom", size: "200x200", crop: "pad", gravity: "center" %>
            <% end %>
          </div>
          <div class="card-information">
            <h5><%= parti.nom %></h5>
          </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/partis/show.html.erb
<% provide(:title, @parti.nom) %>

<% if @parti.photo.attached? %>
  <div class="text-center">
    <%= cl_image_tag @parti.photo.key, width: "290" %>
  </div>
<% end %>

<div class="line-space"></div>

<div class="parti-nom">
  <h2><%= @parti.nom %></h2>
</div>

<div class="line-space"></div>
<p class="parti-description">
  <%= @parti.rich_description %>
</p>

<div class="line-space"></div>

<h3 class="text-center">Consultez l'avis du parti par rapport aux thématiques suivantes :</h3>
<div class="vertical-cards">
  <% @avis_thematiques.each do |avis_thematique| %>
    <%= link_to avis_thematique_path(avis_thematique), class: "political-card" do %>
        <div class="card-image">
          <% if avis_thematique.thematique.photo.attached? %>
            <%= cl_image_tag avis_thematique.thematique.photo.key, class: "zoom", size: "200x200", crop: "pad", gravity: "center" %>
          <% end %>
        </div>
        <div class="card-information">
          <h5><%= avis_thematique.thematique.titre %></h5>
        </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <%= link_to root_path, id: "icon" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <div class="pc-links">
      <%= link_to "Partis Politiques", partis_path, title: "Partis Politiques" %>
      <%= link_to "Thématiques", thematiques_path, title: "Thématiques" %>
      <%= link_to "Personnalités", personnalites_path, title: "Personnalités" %>
      <%= link_to "Pour aller plus loin...", pour_aller_plus_loin_path, title: "Pour aller plus loin..." %>
      <%= link_to "Qui sommes-nous ?", qui_sommes_nous_path, title: "Qui sommes-nous ?" %>
  </div>
  <div id="dropdown">
    <i class="fas fa-align-justify" style="font-size: 2rem"></i>
  </div>
  <div class="smodal">
    <div class="modal-content">
      <div class="close">
        +
      </div>
      <div class="links">
      <%= link_to "Partis Politiques", partis_path %>
      <%= link_to "Thématiques", thematiques_path %>
      <%= link_to "Personnalités Politiques", personnalites_path %>
      <%= link_to "Pour aller plus loin...", pour_aller_plus_loin_path %>
      <%= link_to "Qui sommes-nous ?", qui_sommes_nous_path %>
      </div>
    </div>
  </div>
</nav>

app/views/sous_thematiques/index.html.erb
<% provide(:title, 'Sous-thématiques') %>
<h1>Sous-thématiques</h1>
<div class="vertical-cards">
  <% @sous_thematiques.each do |thematique| %>
    <%= link_to sous_thematique_path(thematique), class: "political-card" do %>
      <div class="card-image">
        <%= cl_image_tag sous_thematique.photo.key, class: "zoom", size: "180x180", crop: "pad", gravity: "center" %>
      </div>
      <div class="card-information">
        <h5><%= sous_thematique.titre %></h5>
      </div>
    <% end %>
  <% end %>
</div>

app/views/sous_thematiques/show.html.erb
<% provide(:title, @sous_thematique.titre) %>

<% if @sous_thematique.photo.attached? %>
  <div class="image-container">
    <%= cl_image_tag @sous_thematique.photo.key, class: "image-align" %>
  </div>
<% end %>

<h1><%= @sous_thematique.titre %></h1>

<p class="page-explanation">Affinez votre recherche en ajoutant les partis politiques qui vous intéressent par rapport au sujet <%= @sous_thematique.titre %> :</p>
<%= form_tag("/thematiques/#{@sous_thematique.thematique.id}/sous_thematiques/#{@sous_thematique.id}", method: "get", cache: false, class: "search-form") do %>
  <div>
    <%= select_tag :search, options_from_collection_for_select(@partis, :id, :nom, params[:search]), multiple: true, value: params[:search], class: 'multi' %>
  </div>
  <div>
    <%= submit_tag("Rechercher", class: "custom-search-button") %>
  </div>
<% end %>

<%# if !params[:search].nil? %>
  <div class="cards-horizontal">
    <% @avis_sous_thematiques.each do |avis_sous_thematique| %>
      <div class="political-card-horizontal" >
        <div class="card-image-political">
          <% if avis_sous_thematique.parti.photo.attached? %>
            <%= cl_image_tag avis_sous_thematique.parti.photo.key, class: "zoom", size: "200x200", crop: "pad", gravity: "center" %>
          <% else %>
            <%= avis_sous_thematique.parti.nom %>
          <% end %>
        </div>
        <div class="card-information-horizontal">
          <%= avis_sous_thematique.rich_avis %>
        </div>
      </div>
    <% end %>
  </div>
<%# end %>

app/views/thematiques/index.html.erb
<% provide(:title, 'Thématiques') %>
<h1>Thématiques</h1>
<p class="page-explanation">Sur cette page, vous pourrez comparer les programmes de plusieurs partis sur un sujet en particulier. Par exemple, en cliquant sur "Affaires Étrangères", puis "Europe", vous aurez la possibilité de comparer les programmes de différents partis sur ce sujet.
</p>
<p class="page-explanation">Survolez ou cliquez sur une thématique pour avoir un aperçu des sujets inclus dans celle-ci.</p>
<div class="vertical-cards">
  <% @thematiques.each do |thematique| %>
    <div class="thematique-cardholder">
      <div class="thematique-card-front">
        <div class="card-image">
          <% if thematique.photo.attached? %>
            <%= cl_image_tag thematique.photo.key, class: "zoom", size: "180x180", crop: "pad", gravity: "center" %>
          <% end %>
        </div>
        <div class="card-information">
          <h5><%= thematique.titre %></h5>
        </div>
      </div>
      <div class="thematique-card-back">
        <ul>
        <% thematique.sous_thematiques.each  do |sous_thematique| %>
          <li><%= sous_thematique.titre %></li>
        <% end %>
        </ul>
        <%= link_to "En savoir plus", thematique_path(thematique), class: "custom-search-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/thematiques/show.html.erb
<% provide(:title, @thematique.titre) %>
<h1><%= @thematique.titre %></h1>
<p><%= @thematique.description %></p>

<div class="vertical-cards">
  <% @sous_thematiques.each do |sous_thematique| %>
    <%= link_to thematique_sous_thematique_path(sous_thematique.thematique, sous_thematique), class: "political-card" do %>
      <div class="card-image">
        <% if sous_thematique.photo.attached? %>
          <%= cl_image_tag sous_thematique.photo.key, class: "zoom", size: "180x180", crop: "pad", gravity: "center" %>
        <% end %>
      </div>
      <div class="card-information">
        <h5><%= sous_thematique.titre %></h5>
      </div>
    <% end %>
  <% end %>
</div>